const Products = [
    {
        id: 1,
        image:'/product02.jpg',
        alt: "Front of men's Basic Tee in Aspen White.",
        link: "Aspen White",
        color: "Black",
        price: "$35",
      },
  {
    id: 2,
    image:'/product01.jpg',
    alt: "Front of men's Basic Tee in black.",
    link: "Basic Tee",
    color: "Black",
    price: "$35",
  },
  {
    id: 3,
    image:'/product03.jpg',
    alt: "Front of men's Basic Tee in Charcoal.",
    link: "Charcoal",
    color: "Black",
    price: "$35",
  },
  {
    id: 4,
    image:'/product04.jpg',
    alt: "Front of women's Basic Tee in Iso Dots.",
    link: "Iso Dots",
    color: "Black",
    price: "$35",
  },
  {
    id: 5,
    image:'/product01.jpg',
    alt: "Front of men's Basic Tee in black.",
    link: "Basic Tee",
    color: "Black",
    price: "$35",
  },
  {
    id: 6,
    image:'/product02.jpg',
    alt: "Front of men's Basic Tee in Aspen White.",
    link: "Aspen White",
    color: "Black",
    price: "$35",
  },
  {
    id: 7,
    image:'/product03.jpg',
    alt: "Front of men's Basic Tee in Charcoal.",
    link: "Charcoal",
    color: "Black",
    price: "$35",
  },
  {
    id: 8,
    image:'/product04.jpg',
    alt: "Front of women's Basic Tee in Iso Dots.",
    link: "Iso Dots",
    color: "Black",
    price: "$35",
  },
];

export { Products };
